type: chase
url: https://chase.com
steps:
  - name: Navigate to login page if needed
    timeout: 5000
    selector:
      cssSelector: a.signInBtn
      isOptional: true
      actions:
        - type: click
  - name: Enter username
    timeout: 5000
    selector:
      cssSelector: input[name='userId']
      iFrameSelector: iFrame#logonbox
      actions:
        - type: sendKeys
          send: username
  - name: Enter password
    selector:
      cssSelector: input[name='password']
      iFrameSelector: iFrame#logonbox
      actions:
        - type: sendKeys
          send: password
  - name: Sign-in
    selector:
      cssSelector: button[type='submit']
      iFrameSelector: iFrame#logonbox
      actions:
        - type: click
  - name: Navigate to offers
    timeout: 120000
    selector:
      cssSelector: div[data-testid='offer-carousel-header-container']
      actions:
        - type: click
  - name: Open card dropdown
    selector:
      cssSelector: "#select-credit-card-account"
      actions:
        - type: click
  - name: Iterate over cards
    type: forEach
    selector:
      cssSelector: "#select-credit-card-account > mds-select-option"
      actions:
        - type: count
          variableName: cardCount
    indexVariable: cardIndex
    loopCountVariable: cardCount
    forEach:
      - name: Select next card
        selector:
          cssSelector: "#select-credit-card-account > mds-select-option:nth-child({index})"
          templateReplacers:
            "{index}": cardIndex
          actions:
            - type: text
              regexCaptureGroups:
                name: "^[^,]+"
              storeUnder: "cards.{cardIndex}"
              templateReplacers:
                "{cardIndex}": cardIndex
              variableName: card
            - type: click
      - name: Activate new offers
        selector:
          cssSelector: mds-icon[type='ico_add_circle']
          isOptional: true
          actions:
            - type: click
        indexVariable: offerIndex
        whileFound:
          - name: Get offer details
            selector:
              cssSelector: div[data-testid='offerAmount']
              actions:
                - type: text
                  regexCaptureGroups:
                    amount: "\\d+"
                    unit: "[%\\$]"
                    type: "[a-zA-Z].+$"
                  storeUnder: "cards.{cardIndex}.card.offers.{offerIndex}"
                  templateReplacers:
                    "{cardIndex}": cardIndex
                    "{offerIndex}": offerIndex
                  variableName: offer
          - name: Get offer store
            selector:
              cssSelector: "#content > div > div:nth-child(3) > div > div:nth-child(2) > div > div > div:nth-child(2) > h2"
              actions:
                - type: text
                  storeUnder: "cards.{cardIndex}.card.offers.{offerIndex}"
                  templateReplacers:
                    "{cardIndex}": cardIndex
                    "{offerIndex}": offerIndex
                  variableName: store
          - name: Get offer expiration
            selector:
              cssSelector: "#content > div > div:nth-child(3) > div > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(2) > div > div >div > div:nth-child(2) > span"
              actions:
                - type: text
                  storeUnder: "cards.{cardIndex}.card.offers.{offerIndex}"
                  templateReplacers:
                    "{cardIndex}": cardIndex
                    "{offerIndex}": offerIndex
                  variableName: expires
          - name: Return to offers
            selector:
              cssSelector: "#mds-secondary-back-navbar"
              shadowRootCSSSelector: "#back-button"
              actions:
                - type: click
      - name: Open card dropdown
        selector:
          cssSelector: "#select-credit-card-account"
          actions:
            - type: click
